version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - laravel

    db:
        image: mysql:8.0
        platform: linux/arm64
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
